spring.application.name=iam_service
server.servlet.context-path=/

server.port=8189

#Jwt
jwt.secret=x+uG+vBZeRsJ2AaW0TS6F9qO8KA9LvDZh4g3hp9Fo3PYFkYPBeszAYv0dFHaIz3SI58iCho/t4L6NR6Tp3Ri6A==
jwt.lifetime=3600000
jwt.expiration=103600000


#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/post_hub_local
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Jpa
spring.jpa.properties.hibernate.default_schema=v1_iam_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_iam_service

#End-point strings:
end.point.posts=/posts
end.point.id=/{id}
end.point.create=/create
end.point.all=/all
end.point.search=/search
end.point.users=/users

#Logging level
logging.level.com.post_hub.iam_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG